server:
  port: 8081

aliyun:
  sls:
    log:
      project: my-springboot-starter
      endpoint: cn-guangzhou.log.aliyuncs.com
      enabled: false
#      log-store: my-local
spring:
  application:
    name: platform-web