spring:
  application:
    name: platform-web
  datasource:
    url: jdbc:mysql://localhost:3306/basic_platform?allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: mysql8@2022
    type: com.mysql.cj.jdbc.MysqlDataSource

server:
  port: 8081

aliyun:
  sls:
    log:
      project: my-springboot-starter
      endpoint: cn-guangzhou.log.aliyuncs.com
      enabled: false
      log-store: my-local


web:
  log:
    lever: INFO
    filter:
      exclude-patterns:
        - /base/test/2
        - /base/abc
#      include-patterns:
#        - /base/printSlsLog
#        - /base/test
#        - /base/abc

debug: false

log:
  lever: INFO
dao:
  sql:
    log:
      normal-sql-log-level: info
      enabled: false


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

#logging:
#  config: classpath:logback-spring.xml